title: My Knowledge Base
theme: just-the-docs

# Optional settings:
logo: "/assets/logo.png"
color_scheme: light

# Enable tree-style sidebar
just_the_docs:
  collections:
    network:
      name: "Network"
      nav_fold: true
    linux:
      name: "Linux"
      nav_fold: true
    other:
      name: "Other"
      nav_fold: true
