name: Update Navigation Automatically

on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'generate_filelist.py'

jobs:
  update_navigation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.AUTO_UPDATER_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run filelist generator
      run: |
        python generate_filelist.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add content/filelist.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update navigation"
        git push