name: Update Navigation Automatically

on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'generate_filelist.py'

jobs:
  update_navigation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important: fetches full history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install watchdog  # For better file detection

    - name: Run filelist generator (force update)
      run: |
        echo "Force regenerating filelist.json"
        python generate_filelist.py
        cat content/filelist.json  # Debug output

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add content/filelist.json
        git status  # Debug output
        git diff --cached --quiet || (git commit -m "Auto-update navigation" && git push)